steps:
- name: node
  entrypoint: npm
  args: ['install', '@vue/cli']
- name: node
  entrypoint: npm
  args: ['install', '@vue/cli-service']
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"